service: az-ad-lambda-authn
frameworkVersion: '3'
provider:
  name: aws
  stage: ${env:AWS_STAGE}
  region: ${env:AWS_REGION}
  runtime: nodejs14.x
  memorySize: 128
  httpApi:
    cors:
      allowedOrigins:
        - "*" # Solo modo ejemplo
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
      maxAge: 6000
    shouldStartNameWithService: true
    authorizers:
      customAuthn:
        functionName: authn
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: 'https://login.microsoftonline.com/${env:AZURE_TENANT_ID}/v2.0'
        audience:
          - ${env:AZURE_CLIENT_ID}
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: customAuthn
            scopes:
              - api-access
  authn:
    handler: authn/index.handler
    environment:
      AZURE_TENANT_ID: '${env:AZURE_TENANT_ID}'
      AZURE_CLIENT_ID: '${env:AZURE_CLIENT_ID}'
      AZURE_VERSION: 'v2.0'
